# Generated by Django 3.0.5 on 2020-04-11 20:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jitsi_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('slug', models.CharField(max_length=200)),
                ('host_user_id', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'parties',
                'unique_together': {('jitsi_id', 'slug')},
            },
        ),
    ]
