# Generated by Django 3.0.5 on 2020-04-12 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PomodoroTimer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_type', models.IntegerField()),
                ('owner_id', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('focus_starts_at', models.IntegerField()),
                ('focus_ends_at', models.IntegerField()),
                ('break_starts_at', models.IntegerField()),
                ('break_ends_at', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'pomodoro_timers',
                'index_together': {('active', 'owner_type', 'owner_id', 'focus_starts_at')},
            },
        ),
    ]
