# Generated by Django 3.0.5 on 2020-04-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20200412_0249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partymember',
            old_name='joined_at',
            new_name='last_joined_at',
        ),
        migrations.RenameField(
            model_name='partymember',
            old_name='left_at',
            new_name='last_left_at',
        ),
        migrations.AddField(
            model_name='party',
            name='max_member_count',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterIndexTogether(
            name='partymember',
            index_together={('user_id', 'active')},
        ),
    ]
