# Generated by Django 3.0.5 on 2020-04-12 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_auto_20200412_0359'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='party',
            index_together={('active', 'host_user_id')},
        ),
    ]
