# Generated by Django 3.0.5 on 2020-04-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_auto_20200412_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partymember',
            name='last_left_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
