# Generated by Django 3.0.5 on 2020-04-12 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_auto_20200412_0633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pomodorotimer',
            name='break_ends_at',
        ),
        migrations.RemoveField(
            model_name='pomodorotimer',
            name='break_starts_at',
        ),
        migrations.RemoveField(
            model_name='pomodorotimer',
            name='focus_ends_at',
        ),
        migrations.RemoveField(
            model_name='pomodorotimer',
            name='focus_starts_at',
        ),
    ]
