# Generated by Django 3.0.5 on 2020-04-12 10:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_auto_20200412_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='pomodorotimer',
            name='break_ends_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pomodorotimer',
            name='break_starts_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pomodorotimer',
            name='focus_ends_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pomodorotimer',
            name='focus_starts_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
